version: '3.1'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 15692:15692
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root